---

- name: "configuration play." 
  hosts: web
  # no_log: true
  any_errors_fatal: true
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "Wait 15 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 15
    - name: Check for Python
      ansible.builtin.raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: python3_test
    - name: "Install python3 for Ansible."
      ansible.builtin.raw: apt -y update && apt install -y python3-minimal
      when: python3_test.rc != 0

  roles:
    - configure-server