---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  # Get the environment variables from CircleCI and add to the EC2 instance
  # These env vars will be loaded by the process manager PM2
  environment:
    - NODE_ENV: "{{ lookup('ansible.builtin.env', 'NODE_ENV')}}"
    - TYPEORM_CONNECTION: "{{ lookup('ansible.builtin.env', 'TYPEORM_CONNECTION')}}"  
    - TYPEORM_HOST: "{{ lookup('ansible.builtin.env', 'TYPEORM_HOST')}}" 
    - TYPEORM_PORT: "{{ lookup('ansible.builtin.env', 'TYPEORM_PORT')}}" 
    - TYPEORM_USERNAME: "{{ lookup('ansible.builtin.env', 'TYPEORM_USERNAME')}}" 
    - TYPEORM_PASSWORD: "{{ lookup('ansible.builtin.env', 'TYPEORM_PASSWORD')}}" 
    - TYPEORM_DATABASE: "{{ lookup('ansible.builtin.env', 'TYPEORM_DATABASE')}}" 
    - TYPEORM_ENTITIES: "{{ lookup('ansible.builtin.env', 'TYPEORM_ENTITIES')}}" 
    - TYPEORM_MIGRATIONS: "{{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS')}}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS_DIR')}}"
    - LATEST_BUILD_IDENTIFIER: "{{ lookup('ansible.builtin.env', 'LATEST_BUILD_IDENTIFIER')}}"
  roles:
    - deploy