---

- hosts: server
  user: ubuntu
  roles:
  - prometheus-server
  vars:
    prometheus_config_dir: /etc/prometheus
    prometheus_db_dir: /var/lib/prometheus
    prometheus_binary_local_dir: /usr/local/bin
    prometheus_config_file: 'prometheus.yml.j2'
    prometheus_web_listen_address: "0.0.0.0:9090"
    prometheus_storage_retention: "15d"
    prometheus_storage_retention_size: "5GB"
    prometheus_read_only_dirs: []
    # prometheus_alert_rules_files:
    #   - prometheus/rules/*.rules
    # prometheus_web_external_url: ''
    # prometheus_web_config:
    #   tls_server_config: {}
    #   http_server_config: {}
    #   basic_auth_users: {}
    prometheus_global:
      scrape_interval: 1s
      # scrape_timeout: 10s
      evaluation_interval: 1s
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - $EC2_HOST:9100
    prometheus_scrape_configs:
      - job_name: "node"
        # metrics_path: "{{ prometheus_metrics_path }}"
        ec2_sd_configs:
          - region: $AWS_DEFAULT_REGION
            access_key: $AWS_ACCESS_KEY_ID
            secret_key: $AWS_SECRET_ACCESS_KEY
            port: 9100
  environment:
    - EC2_HOST: "{{ lookup('ansible.builtin.env', 'EC2_HOST') }}"
    - AWS_DEFAULT_REGION: "{{ lookup('ansible.builtin.env', 'AWS_DEFAULT_REGION')}}"
    - AWS_ACCESS_KEY_ID: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"  
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}" 