---

- name: Copy backend files
  become: true
  ansible.builtin.unarchive:
    src: "/home/circleci/project/backend.tar.gz"
    dest: /var/www/

- name: PM2 start app 
  ansible.builtin.shell: |
    pm2 start --name udapeople npm -- start
  args:
    chdir: /var/www/backend/dist
    executable: /bin/bash


