Description: >
  UdaPeople backend stack.

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String
    Default: cli803394216630

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Sub 'udapeopleSG-${WorkflowID}'
      KeyName: '{{resolve:secretsmanager:UdaPeopleSSH:SecretString:keyname}}'
      ImageId: ami-0c4f7023847b90238  # Ubuntu Server 20.04 LTS (HVM), SSD Volume Type (64-bit (x86))
      Tags:
        - Key: Name
          Value: !Sub 'backend-${WorkflowID}'
