AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template for creating an Amazon RDS DB 
Parameters:
  resourceID:
    Description: Unique identifier.
    Type: String
  DBClass:
    Default: db.t3.small
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
Resources:
  backendDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: '{{resolve:secretsmanager:UdaPeopleDB:SecretString:dbname}}'
      Engine: postgres
      EngineVersion: "12.10"
      MasterUsername: '{{resolve:secretsmanager:UdaPeopleDB:SecretString:username}}'
      DBInstanceClass:
        Ref: DBClass
      DBSecurityGroups:
      - Ref: DBSecurityGroup
      AllocatedStorage:
        Ref: DBAllocatedStorage
      MasterUserPassword: '{{resolve:secretsmanager:UdaPeopleDB:SecretString:password}}'
      PubliclyAccessible: true
      DBInstanceIdentifier: !Sub 'backendDB-${resourceID}'
      Tags:
        - Key: Name
          Value: !Sub 'backendDB-${resourceID}'
# RDS Security Group
  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        EC2SecurityGroupName: !Sub 'ec2SecurityGroup-${resourceID}'
      GroupDescription: UdaPeople DB Security Group


