Description: >
  Nested top level Stack Update version 1.3
  S3 Bucket Policy attachment. Must be run by an admin IAM user. 
Parameters:
  resourceID:
    Description: Unique identifier.
    Type: String

Resources: 
  compliance:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        resourceID: !Ref resourceID
      TemplateURL: security_v1.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-compliance-${resourceID}'
  rdspostgres:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      Parameters:
        resourceID: !Ref resourceID
      TemplateURL: rds.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-rdspostgres-${resourceID}'
  ec2backend:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      Parameters:
        resourceID: !Ref resourceID
      TemplateURL: backend.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-backend-${resourceID}'
  s3frontend:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      Parameters:
        resourceID: !Ref resourceID
      TemplateURL: frontend.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-frontend-${resourceID}'
  # cdn:
  #   Condition: CloudFrontAvailable
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: 
  #     - s3frontend
  #   Properties:
  #     Parameters:
  #       resourceID: !Ref resourceID
  #     TemplateURL: cloudfront.yaml
  #     Tags:
  #       - Key: Name
  #         Value: !Sub '${AWS::StackName}-cloudfront-${resourceID}'