Description: >
  Nested top level Stack. Must be run by an admin IAM user.
Parameters:
  resourceID:
    Description: Unique identifier.
    Type: String
  useCloudfront: 
    Description: Choose if CloudFront Distribution is to serve the Web application content.
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"


Resources: 
  compliance:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        resourceID: !Ref resourceID
      TemplateURL: security.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-compliance-${resourceID}'
  rdspostgres:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      Parameters:
        resourceID: !Ref resourceID
      TemplateURL: rds.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-rdspostgres-${resourceID}'