Description: >
  Nested top level Stack Update version 3.
  S3 Bucket Policy attachment. Must be run by an admin IAM user. 
Parameters:
  resourceID:
    Description: Unique identifier.
    Type: String
  Use_Cloudfront: 
    Description: create cloudfront
    Type: Boolean
    Default: false
Resources: 
  compliance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: security_v1.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-compliance-${resourceID}'
  rdspostgres:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      TemplateURL: rds.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-rdspostgres-${resourceID}'
  ec2backend:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      TemplateURL: backend.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-backend-${resourceID}'
  s3frontend:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      TemplateURL: frontend.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-frontend-${resourceID}'
  cdn:
    Type: AWS::CloudFormation::Stack
    Condition: !Ref Use_Cloudfront
    DependsOn: 
      - s3frontend
    Properties:
      TemplateURL: cloudfront.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-cloudfront-${resourceID}'