Description: >
  UdaPeople top level Stack. Must be run by an admin IAM user.
Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String
    Default: cli803394216630
Resources: 
  compliance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: security.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-compliance-${WorkflowID}'
  rdspostgres:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - compliance
    Properties:
      TemplateURL: rds.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-rdspostgres-${WorkflowID}'