---

- name: cleanup backend oldworkflow
  become: true
  ansible.builtin.shell: |
    find /var/www -type d -name "build-*" >> builds.txt
    NUMBER_OF_BUILDS=$(grep -c ^ builds.txt)
    n=$(seq $NUMBER_OF_BUILDS)
    for i in $n
    do
      # get build directory
      BUILD_DIRECTORY=$(sed -n "$i"p builds.txt)
      if [ $BUILD_DIRECTORY != "/var/www/build-${LATEST_BUILD_IDENTIFIER}" ]; then
        sudo rm -rf $BUILD_DIRECTORY
      fi
    done
  args:
    executable: /bin/bash
