---
- name: Assert usage of systemd 
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version

- name: Set systemd version fact
  set_fact:
    alertmanager_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/prometheus/alertmanager/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set alertmanager version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        alertmanager_version: "{{ _latest_release.json.tag_name[1:] }}"
        alertmanager_checksum_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/sha256sums.txt"
- block:
    - name: "Get checksum list"
      set_fact:
        __alertmanager_checksums: "{{ lookup('url', 'https://github.com/prometheus/alertmanager/releases/download/v' + alertmanager_version + '/sha256sums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for amd64 architecture"
      set_fact:
        __alertmanager_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __alertmanager_checksums }}"
      when:
        - "('linux-amd64.tar.gz') in item"
  delegate_to: localhost

# - name: Fail when there are no receivers defined
#   fail:
#     msg: "Configure alert receivers (`alertmanager_receivers`). Otherwise alertmanager won't know where to send alerts."
#   when:
#     - alertmanager_config_file == 'alertmanager.yml.j2'
#     - alertmanager_receivers == []

# - name: Fail when there is no alert route defined
#   fail:
#     msg: "Configure alert routing (`alertmanager_route`). Otherwise alertmanager won't know how to send alerts."
#   when:
#     - alertmanager_config_file == 'alertmanager.yml.j2'
#     - alertmanager_route == {}
- name: "Set slack webhook url fact"
  set_fact:
    slack_webhook_url: "{{ lookup('ansible.builtin.env', 'PROMETHEUS_SLACK_WEBHOOK_URL') }}"
- name: "Set slack default channel fact"
  set_fact:
    slack_default_channel: "{{ lookup('ansible.builtin.env', 'PROMETHEUS_SLACK_CHANNEL') }}"