---

- name: cleanup backend files
  become: true
  ansible.builtin.shell: |
    if [ -f "/var/www/build-${LATEST_BUILD_IDENTIFIER}" ]; then
      sudo rm -rf /var/www/build-${LATEST_BUILD_IDENTIFIER}
    fi
  args:
    executable: /bin/bash

- name: PM2 delete app 
  ansible.builtin.shell: |
    pm2 delete udapeople
  args:
    executable: /bin/bash