---

- import_tasks: pretasks.yml
- import_tasks: install.yml
  become: true
- import_tasks: configure.yml
  become: true
- name: ensure prometheus service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true